version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_VERSION=0.1.0
      - MODEL_URI=yolov8n.pt
      - CORS_ORIGINS=*
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    volumes:
      - ./models:/app/models
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alerts.yml:/etc/prometheus/alerts.yml
      - prometheus-data:/prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--web.enable-lifecycle", "--web.enable-admin-api", "--storage.tsdb.path=/prometheus"]
    ports:
      - "9090:9090"
    depends_on:
      - api
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./models:/models
      - ./mlflow.db:/mlflow.db
    command: mlflow ui --host 0.0.0.0 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlruns
volumes:
  mongo-data:
  prometheus-data:
  grafana-data:
